aeron-io/simple-binary-encoding

- main/java/uk/co/real_logic/sbe/generation/cpp98/Cpp98Generator.java
This PR addresses this ticket Issue #250.
thanks.
> Adding namespace to include guard in order to avoid name collisions.

- main/java/uk/co/real_logic/sbe/generation/python/PythonGenerator.java
Fixes bug described in issue 235. Bits are written back to buffer correctly after modification
> Fix for issue 235

- main/java/uk/co/real_logic/sbe/generation/python/PythonGenerator.java
Includes 2 changes as suggested by Bud Bach
1. Use instance variables instead for class variables for added flexibility
2. Fix bug in setPosition()
> Instance variables and setPosition() fix

- README.md
- examples/python/.gitignore
- examples/python/README.md
- examples/python/decode_example.py
- examples/python/encode_example.py
Not integrated into the build but atleast it gives people an idea of how to use the python generator.
I'll try to write up a python section for the wiki when I get a chance.
> [python] Add python example

- sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleTokenListener.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/NamespaceOutputManager.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/json/JsonTokenListener.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/xml/Field.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/xml/Message.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1066 Collapsible if statements should be merged
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1066
Please let me know if you have any questions.
Zeeshan
> Collapsible if statements should be merged

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaUtil.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/JavaGeneratorTest.java
PoC for #357
Generate toString and appendTo(StringBuilder) method for generated components, targeting light one-liner display.
Sample result:
\[Car](sbeTemplateId=1|sbeSchemaId=1|sbeSchemaVersion=1|sbeBlockLength=41):serialNumber=12345|modelYear=2005|available=T|code=A|someNumbers=[0,1,2,3,4]|vehicleCode=abcdef|extras={sunRoof,sportsPack}|engine=[capacity=4200|numCylinders=8|manufacturerCode=abc]|fuelFigures={[speed=30|mpg=35.9][speed=55|mpg=49.0][speed=75|mpg=40.0]}|performanceFigures={[octaneRating=95|acceleration={[mph=30|seconds=4.0][mph=60|seconds=7.5][mph=100|seconds=12.2]}][octaneRating=99|acceleration={[mph=30|seconds=3.8][mph=60|seconds=7.1][mph=100|seconds=11.8]}]}|make=MAKE|model=MODEL|
Change-Id: I3b45eb18c24ddbc3d6b4c278b38e677d4f6245ed
> [Java] toString generation for debugging purpose

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaUtil.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/EncodedCarTestBase.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/ToStringTest.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/json/JsonPrinterTest.java
Use the following conventions:
* () for sub-messages (composites, group instances)
* [,] for arrays and repeating group
* {,} for sets
> [Java] Rationalize display format

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/ToStringTest.java
e.g. was fuelFigures=] (rather than fuelFigures=[]) in  #360
> [Java] Fix empty group display

- CMakeLists.txt
- sbe-tool/src/main/cpp/otf/OtfMessageDecoder.h
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppUtil.java
> Don't generate trailing ; on namespaces

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
> [C++]: Simplify bool method returns

- .gitignore
- config/suppress.xml
- gocode/Makefile
- gocode/README.md
- gocode/resources/example-extension-2-schema.xml
- gocode/resources/group-with-data-extension-schema.xml
- gocode/resources/simple.xml
- gocode/src/baseline/Car_test.go
- gocode/src/basic/SBE tests/ENUM_test.go
- gocode/src/basic/SBE tests/Message1_test.go
- gocode/src/basic/SBE tests/SET_test.go
- gocode/src/composite/Composite_test.go
- gocode/src/composite_elements/Message_test.go
- gocode/src/example-schema/CarExample.go
- gocode/src/example-schema/CarExample_test.go
- gocode/src/group/SBE tests/TestMessage1_test.go
- gocode/src/group_with_data/TestMessages_test.go
- gocode/src/group_with_data_extension/Extension_test.go
- gocode/src/simple/simple_test.go
- gocode/src/vardata/SBE tests/TestMessage1_test.go
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
This release is mostly functionally complete but see gocode/README.md for next steps. Note, there are API Changes and added methods.
Handle extension logic so that schemas may be extended.
Implement Deprecated().
General code improvements/refactoring.
Vastly improve group handling code.
Add helper methods to choices.
Add much more testing with bug fixes.
Properly introduce range checking on encode/decode so we can better check for correctness.
Improve the documentation/design doc.
Improve the build environment (but see README.md)
Add some initial benchmark cases before beginning performance work.
Fix go fmt - generated code is now clean.
> golang backend phase2

- .gitignore
- csharp/.nuget/SBE.nuspec
- csharp/.nuget/do-release.sh
- csharp/.nuget/examples/CarExample.cs
- csharp/.nuget/examples/baseline/Car.cs
- csharp/.nuget/examples/baseline/VarStringEncoding.cs
- csharp/README.md
- csharp/csharp.sln
- csharp/sbe-samples/CarExample.cs
- csharp/sbe-samples/ExtensionExample.cs
- csharp/sbe-samples/Program.cs
- csharp/sbe-samples/sbe-samples-car.csproj
- csharp/sbe-samples/sbe-samples-extension.csproj
- csharp/sbe-tests/sbe-tests.csproj
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
* Add an iterator for repeating groups
* Modify the example code so that for repeating groups it shows the usage of
iterators, loops, and Next().
* Update the roadmap and status
* Freshen example code, fix and improve build script and doc.
* Freshen nuget package Microsoft.NET.Test.Sdk
* Make the Car and Extension projects be applications so we can
debug them in Visual Studio.
* Remove now defunct Solution Items project
> dotnet support alpha2

- sbe-benchmarks/src/main/cpp/SbeCarCodecBench.h
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Reverts real-logic/simple-binary-encoding#503
Broken build.
> Revert "Remove inefficiencies created by introducing specific C++11"

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
This is the start of work on #289/#22. I've got a couple of questions, and I thought it'd be easier to ask with the code to look at (questions are inline on the changes). Any feedback on if I'm barking up the right tree would be appreciated as well!
> [Java] Start of writing Javadocs

- csharp/sbe-tests/Issue564Tests.cs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
> [C#] Check max group size not exceeded #564

- csharp/.nuget/SBE.nuspec
- csharp/.nuget/do-release.sh
- csharp/README.md
> nuget release

- .travis.yml
- README.md
This will build and run the tests for the C++ implementation.
> Add Travis ci integration

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
> Lookup blockLength and numInGrp rather than assuming positions

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
> [C++] Non-printable CHAR printed as int

- build.gradle
- config/checkstyle/checkstyle.xml
checkstyle project need this update to keep using your project in regression testing on each commit.
> bump checkstyle to 8.24; checkstyle config: move LineLenght to Checker

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Methods to read and write underlying set values.
> [C++] Read/write set raw value

- sbe-tool/src/test/cpp/CodeGenTest.cpp
Also update the CodeGenTest to include missing color field.
> [C++] add test to show that display string can be printed at any point during the decode of a message

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Adds the missing line feeds that got pulled in at #758.
> [C++] Formatting

- sbe-benchmarks/src/main/cpp/benchlet-main.cpp
- sbe-benchmarks/src/main/cpp/benchlet.h
Windows.h have a lot of predefined Macros and conflicting with generated files.
> Move include Windows.h into Cpp

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
> Cpp literal improve.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
Fix a small syntax error in array construction
> fix array syntax error

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Minor change, the message headers could be constexpr
> [C++] message header members constexpr

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
- sbe-tool/src/test/cpp/FieldAccessOrderCheckTest.cpp
... when precedence checks are enabled
> [C++] check for not wrapped state in decodeLength()

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/MessageCoderDef.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
> [Rust] Elide explicit ActingVersion lifetime.

- build.gradle
- rust/Cargo.toml
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/test/resources/issue1057.xml
Fix of [issue 1057](https://github.com/aeron-io/simple-binary-encoding/issues/1057)
> [Rust] get proper version for composite types.
