aeron-io/simple-binary-encoding

- main/java/uk/co/real_logic/sbe/generation/python/PythonGenerator.java
This pull request has a couple of minor fixes to the python code generation and a pretty significant change to the enum handling.  My goal was to simplify the enum code and add a feature that allows you to easily retrieve the name of an enum value.  The decoder now returns an instance of the enum class and there is a \_\_str\_\_() instance method that handles the enum value to value name conversion.
Here is an example of a new style generated class:
```python
import struct
class Model:
A = 'A'
B = 'B'
C = 'C'
NULL_VALUE = '\0'
VALID_VALUES = {
A,
B,
C,
NULL_VALUE,
}
AS_TEXT = {
A : 'A',
B : 'B',
C : 'C',
NULL_VALUE : 'NULL_VALUE',
}
def __init__(self, value):
self.value = value
if self.value not in Model.VALID_VALUES:
raise ValueError('Invalid value for Model: {}'.format(value))
def …
```
> [python] Fixes and improvements to enum handling

- main/cpp/sbe/sbe.hpp
Without this, a compiler warning (warning: "__STDC_LIMIT_MACROS"
redefined) is generated when your build system or another library
already defined __STDC_LIMIT_MACROS
> Add define guard to definition of __STDC_LIMIT_MACROS

- main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
When the SBE tool is used to generate Java source, the resulting compilation units cause warnings such as:
The value of the field UpdateBatchDecoder.UpdatesDecoder.actingVersion is not used
The value of the field BondSymbolInfoDecoder.parentMessage is not used
While filtering can be used to ignore such warnings within an IDE, it is preferable to overcome the warnings in a manner that does not require end user intervention.
This PR adopts the simplest possible by solution by adding ``@SuppressWarnings("all")`` to the generated compilation units. Being a ``java.lang`` annotation, this requires no additional import. It has also been available since Java 1.5. While [SuppressWarnings](http://docs.oracle.com/javase/8/docs/api/java/lang/SuppressWarnings.html) does not require a compiler to …
> Overcome warnings in generated Java source compilation units.

- sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleUsingGeneratedStub.java
- sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleUsingGeneratedStubExtension.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/PrimitiveValue.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1943 Classes and methods that rely on default system encoding should not be used
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1943
Please let me know if you have any questions.
Zeeshan
> Classes and methods that rely on default system encoding should not be used

- sbe-samples/src/main/java/uk/co/real_logic/sbe/examples/ExampleTokenListener.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/IrDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/json/JsonTokenListener.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/xml/IrGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/xml/Message.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S2325 private methods that don't access instance data should be static
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2325
Please let me know if you have any questions.
Zeeshan
> private methods that don't access instance data should be static

- sbe-tool/src/main/java/uk/co/real_logic/sbe/SbeTool.java
The docs [here](https://github.com/real-logic/simple-binary-encoding/wiki/Sbe-Tool-Guide) say the output directory defaults to current : "sbe.output.dir: Target directory for output generation, defaults to current directory."
However it attempts to write to /packagename.
Small patch to fix that.
> [Java] default output directory of SbeTool to CWD

- sbe-benchmarks/src/main/cpp/SbeCarCodecBench.h
- sbe-benchmarks/src/main/cpp/SbeMarketDataCodecBench.h
- sbe-tool/src/main/java/uk/co/real_logic/sbe/SbeTool.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppUtil.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/Ir.java
- sbe-tool/src/test/cpp/BoundsCheckTest.cpp
- sbe-tool/src/test/cpp/CodeGenTest.cpp
- sbe-tool/src/test/cpp/CompositeElementsTest.cpp
- sbe-tool/src/test/cpp/CompositeOffsetsCodeGenTest.cpp
- sbe-tool/src/test/cpp/CompositeOffsetsIrTest.cpp
- sbe-tool/src/test/cpp/GroupWithDataTest.cpp
- sbe-tool/src/test/cpp/MessageBlockLengthTest.cpp
- sbe-tool/src/test/cpp/Rc3OtfFullIrTest.cpp
Given a project name `proj.provider.messages` the currently generated C++ code is namespaced into `proj_provider_messages`, which is hardly an expected outcome.
This proposed PR will namespace the stubs properly nested:
namespace proj {
namespace provider {
namespace messages {
......
};
};
};
While it is in the _C++17_ standard to allow the collapsed syntax:
namespace proj::provider::messages {
......
};
It still may take some time to propagate throughout the toolchain, so my suggestion is to stick to the explicit nesting.
This PR addresses #121.
> C++ nested namespaces

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
The pull request addresses the issue #353 and is limited to HeaderStructure data in the stubs.
> [C++]: Static constexpr fields in CppGenerator

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
This continues work from https://github.com/real-logic/simple-binary-encoding/pull/355 to make more constants available during compile time.
> [C++]: More constexpr's where possible

- sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/ByteOrderCodec.h
- sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/FrameCodec.h
- sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/MessageHeader.h
- sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/PresenceCodec.h
- sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/PrimitiveTypeCodec.h
- sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/SignalCodec.h
- sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/TokenCodec.h
- sbe-tool/src/main/cpp/uk_co_real_logic_sbe_ir_generated/VarDataEncoding.h
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Address issue #353, PRs #355, #366
Regenerate IR stubs using the fixed constexpr generator
> Fix #353 #355 #366

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Faster at runtime, less includes.
> Use universal reference instead of paying std::function overhead

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Due to a quirk in C++ int64 minimum value can not be encoded as
literal. You need to use INT64_MIN constant.
> Correctly encode int64 minimum value.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Constant properties now are truly constant, which allows us to perform compile-time usage of them.
Old PR: https://github.com/real-logic/simple-binary-encoding/pull/376. This should be good now.
> [C++]: Make constant fields static constexpr

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
We already expose them for messages, so this shouldn't pose problems.
> [C++]: Expose buffer in fixed flyweights

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
They are not needed because they are generated automatically as long as you don't have destructors and just copying all the fields should be the correct way. They are also invalid as they are because they can't copy an ampty flyweight (one that was constructed with a default constructor). This happens because we try to call `reset` which validates buffer sizes.
> [C++]: Don't generate copy and move constructors and operators

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaUtil.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/JavaGeneratorTest.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/ReflectionUtil.java
Convenience methods for extracting char arrays as String in decoders (and also the symmetric setter in encoders). Declared encoding is used and zero bytes are removed.
> [Java] add new convenience methods to get char arrays as string.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Needed for low-level operations on message buffers, when you want to operate on a part of message representation in memory. For example, this can be used to update changed parts of a message in an external hardware buffer.
> [C++] Add Position and Size values

- README.md
- build.gradle
- gocode/Makefile
- gocode/README.md
- gocode/resources/simple.xml
- gocode/sbe-tool
- gocode/src/baseline-bigendian/Car_test.go
- gocode/src/baseline/Car_test.go
- gocode/src/composite/Composite_test.go
- gocode/src/example-schema/CarExample.go
- gocode/src/example-schema/CarExample_test.go
- gocode/src/example-socket-clientserver/clientserver.go
- gocode/src/mktdata/fixme_test.go
- gocode/src/simple/simple_test.go
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
- sbe-tool/src/main/resources/golang/templates/SbeMarshallingBigEndian.go
- sbe-tool/src/main/resources/golang/templates/SbeMarshallingLittleEndian.go
Much improved documentation moving much content into wiki.
MessageHeader's are now allowed to be any unsigned integer type,
rather than just uint16. This causes a small API change as MessageHeaders
are now generated
Added gradlew generateGolangCodec target to create golang source
code using sbe-tool. This assists windows developers by providing
a convenience target and examples and simplifies the still
linux-centric gnu Makefile.
Add an example using bufio so that reads and writes get merged
for performance.
> Golang beta1, feature complete

- CMakeLists.txt
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Enable extra warnings and fix those warnings.
> Enable extra warnings (-Wextra)

- sbe-tool/src/main/cpp/otf/Encoding.h
Prevents linker errors with multiple defined symbols when including Encoding.h in multiple source files
> Made lengthOfType inline

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
> Partial fix for #437: Use compiler detections to guard pragmas to suppress excessive warnings

- README.md
I spent some hours to understand that I was trying to execute the wrong Jar:  
I was wondering for hours what was wrong in the building process about produced `build/libs/sbe-all-1.7.0.jar` without `META-INF/MANIFEST.MF`... 😞 
I think I am not alone because it was also the issue #324
Instead of creating a new issue to request someone to document that point, I propose in this pull reuest to provide some documentation in the README.md about produced Jars, and also a warning to prevent using the wrong Jars.
It is important to keep the error message *"no main manifest attribute"* within the README.md in case someone is searching this error on the GitHub project or in the web (e.g. googling *"error SBE no main manifest attribute"*). With some luck this person will helpfully find this …
> Explain the produced Jars to avoid missuses

- build.gradle
- gocode/Makefile
- gocode/src/issue472/Issue472_test.go
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
- sbe-tool/src/main/resources/golang/templates/SbeMarshallingBigEndian.go
- sbe-tool/src/test/resources/issue472.xml
Add intialization to NullValue for optional fields.
Allow NullValue for optional fields in RangeCheck.
Add test case.
> Issue472 Handle presence="optional"

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
See #368 
You can see the generate files [here](https://gist.github.com/fracek/82c66357e039eebd09281c562e9cfd29), if I missed anything let me know!
> [C++] Add noexcept specifier

- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/rust/RustFlatFileOutputManagerTest.java
The filesystem manipulation that enables a certain kind of testing of the output manager is not supported when running tests in windows. Uses `assumeTrue` to conditionally ignore the relevant test when said capabilities are absent.
> Use assumeTrue to confirm filesystem manipulation for output manager testing usable

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaUtil.java
The `JavaUtil` class contains a lot of useful methods for creating the customer-specific SBE-based tools . The `generateLiteral(final PrimitiveType type, final String value)` method is a nice addition to this toolbox.
NOTE: any objection to moving the `JavaGenerator.eachField(final List<Token> tokens, final BiConsumer<Token, Token> consumer)` method to the `JavaUtil` too? It is turned public in the current SNAPSHOT so somebody uses it already but it does not feel right to use `JavaGenerator` for utility methods.
> Move the static generateLiteral(...) method from JavaGenerator to JavaUtil and make it public

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
This improves the usability of the `*_from_slice` method of encoding a group of fixed-size members all in one go by removing an unnecessary link between the input slice that will be copied and the output data buffer. The fact that we're copying bytes behind the curtains obviates the need to do more than be sure the slice lives for the duration of the method call.
Preliminary testing also shows an ~10% performance encoding improvement over the immediate alternatives and reduces client-user temptation to apply `unsafe` methods.
@mjpt777
> [Rust] Remove a spurious lifetime from a parameter a slice-encoding method

- rust/car_example/src/main.rs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustCodecType.java
Previously the done-state of generated rust encoders and decoders handed back a reference to the wrapped data buffer and a the final position read/written to. Now only the final position is provided. 
This ensures that it is impossible for the mutable references data struct overlays optionally created during encoding to coexist with a same-lifetime'd mutable byte slice produced at the end.  Since the final position is still returned, and the original input buffers were all slice-references anyhow, users should be able to trivally re-slice the source data equivalently themselves without loss of functionality.
A minor performance gain is also accomplished because returning a `usize` is marginally cheaper than returning a newly-allocated tuple containing a usize and a slice-reference. …
> [Rust] Simplify done unwrapping to prevent dual mutable aliasing

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustCodecType.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/rust/RustGeneratorTest.java
Adds inline explanatory commentary to generated Rust code.
> [Rust] Improve the self-documentation of generated rust code

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
I found an issue when using the java SBE tool to generate C++ code. When generating Array fields within groups the code does not compile due to the return class name on the generated Put methods being set to the group name rather than the class name. The non array fields were ok as the string generation methods call formatClassName for the return type but on the array builder it does not. I couldn't see any reason not to convert to the class name when calling generateFields so did so there.
> [C++ Generator]:Incorrect generation of arrays within groups

- gocode/Makefile
- gocode/src/issue483/Issue483_test.go
- sbe-tool/src/test/resources/issue483.xml
Update the issue483 test case to supply a contant value as it's absence now fails code generation.
Use explicit path to gradlew to not assume '.' is in PATH.
Also reference https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/issues/64 for spec change that might simplify this.
> Issue #532 `make test` in gocode directory fails

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
I think it makes sense to fully spell out "::sbe::MetaAttribute" (and others) in code-generated headers because "using namespace" is typically frowned upon in C++ headers (see: https://isocpp.org/wiki/faq/coding-standards#using-namespace-std). I was able to test this change against the unit tests and my own code.
> [C++] Removed using namespace sbe from code-generated headers

- sbe-tool/src/test/cpp/BoundsCheckTest.cpp
- sbe-tool/src/test/cpp/CodeGenTest.cpp
- sbe-tool/src/test/cpp/CompositeElementsTest.cpp
- sbe-tool/src/test/cpp/CompositeOffsetsCodeGenTest.cpp
- sbe-tool/src/test/cpp/CompositeOffsetsIrTest.cpp
- sbe-tool/src/test/cpp/GroupWithDataTest.cpp
- sbe-tool/src/test/cpp/MessageBlockLengthTest.cpp
- sbe-tool/src/test/cpp/Rc3OtfFullIrTest.cpp
Cleaning up namespaces in C++ unit tests.
Also bumping copyright year while I'm already here.
> [C++] Cleaning up unit tests' global namespaces

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/JavaGeneratorTest.java
This PR allows to set ASCII encoded char array fields with any class implementing CharSequence, not only with Strings. It helps writing GC-free code without handling byte arrays. One for example can pass StringBuilder as an argument which can be shared between invocations.
> [Java] Generate put CharSequence methods for ASCII encoded fields

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/SchemaExtensionTest.java
- sbe-tool/src/test/resources/extension-schema.xml
Generated `if` statement in decoder's methods must use `sinceVersion` from fields declaration, not type declarations.
> [Java] Using sinceVersion from field instead of type declaration

- sbe-tool/src/test/cpp/BoundsCheckTest.cpp
- sbe-tool/src/test/cpp/CodeGenTest.cpp
- sbe-tool/src/test/cpp/CompositeElementsTest.cpp
- sbe-tool/src/test/cpp/CompositeOffsetsCodeGenTest.cpp
- sbe-tool/src/test/cpp/CompositeOffsetsIrTest.cpp
- sbe-tool/src/test/cpp/GroupWithDataTest.cpp
- sbe-tool/src/test/cpp/MessageBlockLengthTest.cpp
- sbe-tool/src/test/cpp/Rc3OtfFullIrTest.cpp
The virtual specifier is not needed in unit test functions because the functions do not get overridden in derived classes. Also, I refactored the Rc3OtfFullIrTest to use constexpr where applicable.
> [C++] Unit test improvements

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
Previously `_actingVersion` was not initialized upon a call to `WrapForEncode(...)`.
This meant that access to properties on the group that allow the items to be encoded fails.
Now we initialize it to the current schema version.
> Fixes an issue associated with issue #543.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/JavaGeneratorTest.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/ReflectionUtil.java
- sbe-tool/src/test/resources/code-generation-schema.xml
This PR allows to read ASCII encoded fixed and variable length strings from generated decoders. This allows for users to pass in a StringBuilder to avoid allocating a string.
> [Java] Add new method to decoders to pass in Appendable to write ascii encoded strings to

- build.gradle
- gocode/Makefile
- gocode/src/baseline-bigendian/Car_test.go
- gocode/src/baseline/Car_test.go
- gocode/src/basic/SBE tests/ENUM_test.go
- gocode/src/basic/SBE tests/Message1_test.go
- gocode/src/basic/SBE tests/SET_test.go
- gocode/src/composite/Composite_test.go
- gocode/src/composite_elements/Message_test.go
- gocode/src/example-schema/CarExample_test.go
- gocode/src/example-socket-clientserver/clientserver.go
- gocode/src/group/SBE tests/TestMessage1_test.go
- gocode/src/group_with_data/TestMessages_test.go
- gocode/src/group_with_data_extension/Extension_test.go
- gocode/src/issue435/Issue435_test.go
- gocode/src/issue472/Issue472_test.go
- gocode/src/issue560/Issue560_test.go
- gocode/src/simple/simple_test.go
- gocode/src/vardata/SBE tests/TestMessage1_test.go
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
- sbe-tool/src/test/resources/issue560.xml
Newer versions of the go compiler check format strings so found a number of
problems.
> Issue560 preparation. Add test case, fix golang format strings.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/csharp/Issue567GroupSizeTest.java
- sbe-tool/src/test/resources/issue567-invalid.xml
- sbe-tool/src/test/resources/issue567-valid.xml
- Unsafely casts `numInGroup` to be an `int` when setting `count` field so that "larger" types than `uint16` may be supported without breaking the existing API
- Checks that the encoding of `numInGroup` does not exceed the range of an `int` at generation time in order to make the above cast safe
- Adds tests around this check
> [C#] support for `uint32` representation of group size

- rust/car_example/src/main.rs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/NamedToken.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/rust/RustGeneratorTest.java
- sbe-tool/src/test/resources/constant-enum-fields.xml
As requested in https://github.com/real-logic/simple-binary-encoding/issues/560
> Handle IR changes to const enums for Rust; re-enable regression tests

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/SchemaExtensionTest.java
- sbe-tool/src/test/resources/extension-schema.xml
If a schema is extended to include a new string field (fixed or variable), the newly generated decoder code not compile due to an error for deserialising the string using appendable; if the "sinceVersion" and "actingVersion" don't line up it tries to return a string on a void method. This commit changes the generated code to just call "return;"
> [Java] Invalid code generated for newly added string field

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
The decoder generated for a Set does not provide a convenience method to determine if nothing has been set. If we look at sbe_samples and Car's OptionalExtras, the only way to determine if no OptionalExtras
have been set is to call 
```
notSet = ! (sunRoof() || sportsPack() || cruiseControl());
```    
And this code is fragile and inefficient. This PR modifies SbeTool to generate a new method in OptionalExtrasDecoder
```
public boolean noChoicesSet()
{
return 0 == buffer.getByte(offset);
}
```
> Generate noChoicesSet convenience method for Sets

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
- In order to avoid copying the whole structure functions should use pointer receiver when possible.
- One exception is for enums, where it makes more sense to keep the copy receivers.
> golang: Use pointer receiver where appropriate

- sbe-tool/src/main/java/uk/co/real_logic/sbe/xml/CompositeType.java
Relates to comment on #615.  Allow signed numInGrp and validate that the minValue is > 0
> Warn instead of error on signed numInGrp, check for minValue < 0

- csharp/README.md
- csharp/netfx.props
- csharp/sbe-dll/DirectBuffer.cs
- csharp/sbe-dll/packages.config
- csharp/sbe-dll/sbe-dll.csproj
- csharp/sbe-tests/packages.config
- csharp/sbe-tests/sbe-tests.csproj
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
- Closes #587
- Add netfx.props and tweak sbxee-dll csproj to allow building sbe.dll
for net45 on Linux using dotnet sdk following:
https://andrewlock.net/building-net-framework-asp-net-core-apps-on-linux-using-mono-and-the-net-cli/
- Remove packages.config files from projects already converted to SDK style project since
those files serve no purpose other than confusing potential contributors...
- Intoroduce minimal Span<byte> GetBytes/SetBytes implementation for copying
to/from Span<byte> to sbe.dll itself.
- Change code generation for array types to use Span<byte> internally keeping the
original functionality intact with no (hopefully!) visible user facing changes except
for the addtitional Get/Set methods accepting Span<byte> being added to the mix.
> In/outgoing Span<byte> support, linux net45 build

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
Fixes https://github.com/real-logic/simple-binary-encoding/issues/613 for Golang implementation.
> [golang] no longer assumes fixed order of group dimension metadata fields

- sbe-tool/src/main/java/uk/co/real_logic/sbe/xml/CompositeType.java
SBE generator currently errors out if schema/template/version fields are not 16 bits.  This PR changes that error to a warning to match the existing validation for blockLength
Similar to #609 and #617
> Header validation warning on non-uint16 types instead of error

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Added std::string_view getter/setter for string-like fields
Added non-const raw access for array like fields
> [c++] Improved field generation

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Deprecated usage of C headers triggers static code analyzers.
> Fix generated includes

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Newly added enum and unions from sbe.h have 5 spaces as indentation as
opposed to 4 like rest of the generated headers.
> [C++] Fix indentation.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/SbeTool.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/xml/XmlSchemaParser.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/xml/RelativeXIncludeTest.java
- sbe-tool/src/test/resources/sub/basic-schema.xml
- sbe-tool/src/test/resources/sub/sub2/common.xml
Allow the resolution of XInclude href's relative to the current directory of the including XML.
> Support file-relative XInclude href's

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/Encoding.java
This PR is created because of violations found during regression testing after implementing [checkstyle](https://github.com/checkstyle/checkstyle/) ability to check multiple lines with comments and javadocs.
Issue: https://github.com/checkstyle/checkstyle/issues/5981
PR: https://github.com/checkstyle/checkstyle/pull/6388
Checkstyle use simple-binary-encoding source code in regression testing.
Testing of checkstyle PR shows places with multiple lines used to separate methods.
You can merge this PR or create your own when checkstyle PR will be merged.
> [Java] fix: remove extra empty lines

- .gitignore
- build.gradle
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
- sbe-tool/src/test/resources/issue661.xml
Cope with the case where actionVersion is less than sinceVersion
by returning a value of '(bitset)0'
> Issue#661 Always return a valid BitSet type

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Other functions (constructor, wrapForEncode) uses bufferLength argument for targeting to memory region [buffer, buffer+bufferLength), not [buffer+offset, buffer+offset+bufferLength).
> [C++] Fix bound check in wrapAndApplyHeader

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
`m_dimensions` is private and just a temporary storage.
> [C++] Remove the dimension member from the codec classes.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/rust/RustGeneratorTest.java
Mimic the Java generator in generating null enum values. The `NullVal`
values are generated even if the enum type is not optional.
> [Rust] Generate NullVal enum values

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
1. Debug can't be derived on packed structs
2. `mut` qualifier unnecessary in `after_member` function
> [Rust] Fix warnings in the generated codec

- build.gradle
- rust/car_example/src/main.rs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustCodecType.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/rust/RustGeneratorTest.java
Fixed a few issues with the Rust codec. Decoders can now handle messages with custom offsets, custom default message header and custom group size encodings. Custom group size is not yet implemented for encoders.
There are also no tests for Rust which would exercise the full encode -> decode cycle. Hopefully I'll get to that and improving encoders when I need to do encoding.
> Rust codec improvements - handle offsets, custom group size encoding

- sbe-samples/src/main/cpp/GeneratedStubExample.cpp
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
To solve issue: https://github.com/real-logic/simple-binary-encoding/issues/178
For GeneratedStubExample it generates json-like string: `{"Name": "Car", "sbeTemplateId": 1, "serialNumber": 1234, "modelYear": 2013, "available": "T", "code": "A", "someNumbers": [0,1,2,3], "vehicleCode": "abcdef", "extras": ["sportsPack","cruiseControl"], "discountedModel": "C", "engine": {"capacity": 2000, "numCylinders": 4, "manufacturerCode": "123", "efficiency": 0, "boosterEnabled": "F", "booster": {"BoostType": "NITROUS", "horsePower": 200}}, "fuelFigures": [{"speed": 30, "mpg": 35.9, "usageDescription": "Urban Cycle"}, {"speed": 55, "mpg": 49, "usageDescription": "Combined Cycle"}, {"speed": 75, "mpg": 40, "usageDescription": "Highway Cycle"}], "performanceFigures": [{"octaneRating": 95, …
> [C++] Generate message pretty printers

- .gitignore
- build.gradle
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustCodecType.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/rust/RustGeneratorTest.java
- sbe-tool/src/test/resources/message-block-length-test.xml
while experimenting with the Rust generator I found a few things that didn't work as expected:
* cargo_exits() in build.gradle wasn't finding cargo
* the 'args' argument should be an array of arguments
* was using `-v` (verbose) instead of `-V` (version).  `-V` is valid by itself while `-v` is not.
* the output went to the screen 
* warnings during `gradlew.bat test`
* caused by a type identifier that was invalid for C#
I cleaned those up and added the ability for rust to decode a header and then pick a template by `template_id`.  This required making some things pub which were private before but I don't think that's an issue.  The code for using this new method looks like this:
```Rust
let (h, buf) = start_decoding_message_header(&buffer)?;
match h.template_id { …
```
> enhancements to Rust generator

- .travis.yml
This will cover everything except Redhat 7 I think.
> Add new compilers

- csharp/sbe-dll/sbe-dll.csproj
- sbe-tool/src/main/java/uk/co/real_logic/sbe/SbeTool.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpNamespaceOutputManager.java
that allows squashing of namespace folder generation
> Add csharp code-gen time property 

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
The accessors for primitive types (including enums) don't throw exceptions so can be marked as noexcept.
> Mark accessors for primitive types as noexcept

- config/checkstyle/checkstyle.xml
Identified at https://github.com/checkstyle/checkstyle/pull/7088 , `allowMissingJavadoc` is deprecated and doesn't do anything anymore as the check was split into 2 and the functionality of the property was moved to `MissingJavadocMethod`.
> remove deprecated allowMissingJavadoc from JavadocMethod

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Removing warnings in generated C++ code, reported by GCC (-Wconversion, -Wsign-conversion) and clang-tidy (using signed integer with a binary bitwise operator).
> [C++] Remove conversion warnings

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Compiler dead store elimination optimization pass should remove any
unncessary  stores  when the codecs are used correctly. With incorrect use
it will give predictable behavior.
> [C++] Make sure all members are initilized

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
`memcpy` is expecting a `size_t` argument, 32-bit builds fail with the following message:
```
error: conversion to ‘size_t {aka unsigned int}’ from ‘uint64_t {aka long long unsigned int}’ may alter its value [-Werror=conversion]
```
Adding explicit cast to silence these errors/warnings.
(IMO it would be better to use `size_t` where byte arrays and offsets are referenced. However this would change the public interface, so didn't want to to this as part of this PR.)
> [C++] Cast memcpy argument to size_t

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaUtil.java
varDataDisplay - use method `getVarFieldName(Appendable)` - no memory allocation. unlike calling method `varFieldName` where it allocates memory (new byte[] and new String).
> [Java] Avoid memory allocation at varDataDisplay

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
This is useful for streaming operations where the final count cannot be determined upfront but it still has a limit. This is a c# implementation in the spirit of the Java one already commited to repo.
You can more easily view an example of this modification here:
https://www.diffchecker.com/LHBJGtnO
> [C#] Support resetting group count to current index.

- build.gradle
- gradle.properties
The following changes were done to the generated artifacts:
- `sbe-tool`:
* exclude Golang sources from all the jars
* include C++ oft headers
- `sbe-all`:
* exclude Golang sources from all the jars
* include C++ oft headers
- `sbe-samples`:
* include generated sources into the jars
* include proper MANIFEST metadata
Other changes include:
- Cleanup build to use helper functions
- Configure HTTP timeouts and retries via Gradle system properties
> [Java] Migrate to `maven-publish` plugin and cleanup artifacts being published

- sbe-benchmarks/src/main/cpp/SbeCarCodecBench.h
The result of the call in the test like
`tmpInt = car.serialNumber();`
is not used, so the optimizer remove that call from the code at all.
There are some ways to avoid this, and the proposed PR fix this problem.
> Fix decoder benchmark.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
Eliminated garbage produced in appendTo for set-based fields to allow full GC-free logging of decoders
> Eliminated garbage produced in appendTo for set-based fields

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Small updates to C++ generator to make Clang-Tidy happy.
> Clang-Tidy fixes

- csharp/sbe-tests/SinceDeprecatedTests.cs
The fix from #763 #23e8c16caf03d2b073bc850f37b1fb68cecbe54a is a winner
> C # Restore the now fixed SinceDeprecated tests. Issue real-logic#763.

- sbe-samples/src/main/cpp/GeneratedStubExample.cpp
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
- sbe-tool/src/test/cpp/CodeGenTest.cpp
- sbe-tool/src/test/cpp/CompositeElementsTest.cpp
Implements: https://github.com/real-logic/simple-binary-encoding/issues/291
> [C++] Methods to calculate the length of an SBE message

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
This adds two new members to the generated C# messages. Both of these are already available in the generated Java classes, but were missing in the C# version.
**`public const int <FieldMember>Offset`**
This is useful if you need to read/write a member with some other method than the generated accessors, e.g. read a fixed-length byte array as a `ReadOnlySpan<byte>`. Currently these offsets need to be hardcoded.
**`public void WrapForEncodeAndApplyHeader(DirectBuffer buffer, int offset, MessageHeader headerEncoder)`**
Generates the repetitive code to fill the header. Same as "wrapAndApplyHeader" in Java.
> [C#] Add Offsets and WrapForEncodeAndApplyHeader

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
> [C#] Generate source documentation from descriptions

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
This PR allows non-default attribute `headerType` in `messageSchema` in xml.
> [C++] add correct message header type as encoder's member type

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
The uint64_t of messageHeader::encodedLength() large than (%1$s), so we need cast to it
> Fixes a cpp warning.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
The C++ code generated for accessing the value of an enumeration was being marked with `SBE_NOEXCEPT` but it invokes the `get()` method for the enumeration, which can throw if the underlying value is not in the supported set of values.
The exception should propagate up to the caller, rather than invoke `std::terminate`
> enum 'get' method is not noexcept

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/FixedSizeDataGeneratorTest.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/JavaGeneratorTest.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/ReflectionUtil.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/SchemaExtensionTest.java
- sbe-tool/src/test/resources/code-generation-schema.xml
- sbe-tool/src/test/resources/extension-schema.xml
There are some cases when message contains byte array of fixed size which is not an ASCII string - e.g. hmac signatures. Declaring them as fixed-size uint8 array currently generates only generic array accessor to put/get one element at a time. Declaring them as strings generate bulk put/get methods which accept byte[], but string semantics - e.g. charset - do not really apply to the field.
This PR adds bulk get/put methods for fixed-length data (described in the "Fixed-length data" section of the spec).
_Encoder_
`public void putData(byte[] buffer, int offset, int length);`
`public void putData(DirectBuffer buffer, int offset, int length);`
These methods behave like var-length counterparts, but pad smaller payloads to the required length with zeros. I couldn't find anything in the spec on …
> [Java] Generate bulk put/get/wrap methods for fixed-length data (uint8 array)

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/c/CGenerator.java
Fixes #822 
Generated C code has a bug in the generated function *_wrap_and_apply_header() It seems like an easy mistake to make as there is very little consistency in argument order between version and bufferLength in the generated code.
> [C] Fixing argument order for *_wrap_and_apply_header

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
This actually broke code I was working on in a very nasty way when the buffer size was too small - I was trying to use the DirectBuffer's bufferOverflow delegate and some bytes were getting eaten when expanding the buffer.
Explanation in the commit msg:
----
On a repeated group in the WrapForEncode, the parentMessage.Limit has two purposes:
1. It is used as a buffer offset for the _dimensions helper Wrap method
2. The assignment to it has a side effect of checking that we do not exceed the underlying DirectBuffer's capacity
However notice that currently this assignment happens after writing to the _dimensions helper properties BlockLength and NumInGroup,
i.e. the writes are done *before* we check for buffer overflow. 
Underneath these are direct writes to the byte* managed by the …
> [C#] Fix repeated group buffer overflow

- gocode/src/group_with_data/TestMessages_test.go
- gocode/src/mktdata/preallocated_test.go
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
This change allows you to call `Decode()` on an sbe struct where the struct has pre-allocated slices. Before, the code would allocate a new slice if the capacity on the existing slice was less than the number of groups in the message. If the old slice had a greater capacity, it wouldn't truncate the number of elements to the new length. The same issue with vardata fields.
> [Go] Fix for decoding into a struct with pre-allocated slices.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/cpp/CppGeneratorTest.java
- sbe-tool/src/test/resources/issue827.xml
> [C++] Use generated literal as the constant one to be shifted in the bitset code.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/JavaGeneratorTest.java
Currently there is no way to extract bounds for repeating group count. This may be necessary for pre-publishing validation code or for the message accepting code which may have some (non-SBE) flyweight buffers for business entities.
> added maximum and minimum meta methods for allowed repeating group count

- build.gradle
- gocode/Makefile
- gocode/src/issue847/issue847_test.go
- gocode/src/issue848/issue848_test.go
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
- sbe-tool/src/test/resources/issue827.xml
- sbe-tool/src/test/resources/issue847.xml
- sbe-tool/src/test/resources/issue848.xml
Adds function `generateWhitespace` which uses the same String.format
technique, but validates the input.  It also always generates at least
one space.
This change should only affect the whitespace of the output.  It does
not attempt to change the logic that might be the underlying cause of #844.
> [Go] GolangGenerator improvements

- build.gradle
- gocode/Makefile
- gocode/src/issue849/issue849_test.go
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
- sbe-tool/src/test/resources/issue849.xml
Too many tokens were passed to `generateComposite` causing weird
errors like(#844 and #849).
Also adds a `gofmt` fix.
> [Go] Fix tokens passed to generateComposite (#849)

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/JavaGeneratorTest.java
- sbe-tool/src/test/resources/deprecated-msg-test-schema.xml
- sbe-tool/src/test/resources/since-deprecated-test-schema.xml
Implementation of #875
Wondering is something similar would make sense for fields?
> Mark classes of deprecated messages with @Deprecated.

- rust/benches/car_benchmark.rs
- rust/benches/md_benchmark.rs
- rust/tests/baseline_test.rs
- rust/tests/big_endian_test.rs
- rust/tests/extension_test.rs
- rust/tests/issue_435_test.rs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/SbeTool.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/LibRsDef.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/MessageCoderDef.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustOutputManager.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustUtil.java
The generated `lib.rs` file now only contains common sbe code, all generated enums, bitSets, composites, etc. will be written to their own file.
> Generating Rust code should support multiple schema files with same package name

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaUtil.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/FrameCodecDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/FrameCodecEncoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/TokenCodecDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/TokenCodecEncoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/xml/EncodedDataType.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/CharacterEncodingTest.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/xml/EncodedDataTypeTest.java
This PR contains several improvements to how charset encoding is handled by the `JavaGenerator`:
- Add support for case-insensitive aliases for standard charsets, e.g. `lAtIN1` will be resolved to `StandardCharsets.ISO_8859_1`. This is similar to how `Charset.forName(String)` works.
- Use `StandardCharsets` when generating static `CharacterEncoding` methods, e.g. `java.nio.charset.StandardCharsets.ISO_8859_1.name()` will be used instead of a string `"latin1"` (when `characterEncoding=latin1`).
- Use canonical names for charsets. The standard charsets are canonical by definition since the constants are used. For non-standard charsets the canonical name is resolved at the code generation time, e.g. if `characterEncoding=cp912` is specified the resolved name will be `ISO-8859-2` and will be …
> [Java] Charset encoding handling improvements.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
Previously, the C++ generated code did not check the version before writing composite and bitset fields to the output stream. This leads to undefined behavior. I've updated the generated code to first check if the field is in the acting version before writing it to the stream.
> C++ code generation: check composite and bitset version

- sbe-tool/src/main/java/uk/co/real_logic/sbe/json/JsonTokenListener.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/json/JsonPrinterTest.java
- sbe-tool/src/test/resources/json-printer-test-schema.xml
When there is no character encoding for vardata (which is normal for binary) JsonPrinter fails with NPE inside string construction with null encoding. Changed behaviour so that hex dump of data is appended instead.
> [Java] Support binary vardata in json printer

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/resources/explicit-package-test-schema.xml
Enhances the test and fixes bugs with embedded composites and REF elements inside composites.
Related to https://github.com/real-logic/simple-binary-encoding/pull/904 and https://github.com/real-logic/simple-binary-encoding/issues/507
> Fix package name support for embedded composites

- build.gradle
- rust/Cargo.toml
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/test/resources/nested-composite-name.xml
I was refactoring the generated Rust codec to be more idiomatic, and discovered that the existing Rust codec generator uses the wrong type name for nested composite field:
Minimal schema file to trigger error:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe"
xmlns:xi="http://www.w3.org/2001/XInclude"
package="nested-composite-name"
id="1"
version="0"
semanticVersion="5.2"
description="test case for nested composite field where the field name from the composite name"
byteOrder="littleEndian">
<types>
<composite name="MyComposite">
<ref name="myFieldName" type="MyNestedComposite"/> 
</composite>
<composite name="MyNestedComposite">
<type name="irrelevantField" primitiveType="uint16"/>
</composite>
<composite name="messageHeader"> …
```
> [Rust] bugfix: nested composite name should not be based on field name

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/c/CGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/golang/GolangGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/FrameCodecDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/FrameCodecEncoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/MessageHeaderDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/MessageHeaderEncoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/TokenCodecDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/TokenCodecEncoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/VarDataEncodingDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/VarDataEncodingEncoder.java
- sbe-tool/src/test/c/CodeGenTest.cpp
- sbe-tool/src/test/cpp/CodeGenTest.cpp
The semantic version is not currently accessible for the clients using the generated stubs. This pull request adds the semantic version as a static public member in the classes generated by the sbe-tool. It is now possible to obtain the value of the sbe template semantic version direct in the source code using the stubs.
> Added semantic version as a static public member

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/LibRsDef.java
Creating a Rust codec and linting the generated code using [clippy](https://doc.rust-lang.org/clippy/index.html) gives the following warning:
```
warning: variables can be used directly in the `format!` string
--> src/lib.rs:123:9
|
123 |         write!(f, "{:?}", self)
|         ^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
= note: `#[warn(clippy::uninlined_format_args)]` on by default
help: change this to
|
123 -         write!(f, "{:?}", self)
123 +         write!(f, "{self:?}")
|
warning: `io_aeron_archive_codecs` (lib) generated 1 warning
```
This PR fixes that.
> [Rust] Fix clippy lint

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/LibRsDef.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/MessageCoderDef.java
Add the `Copy` and `Clone` traits to message decoders.
The Rust [API guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html?highlight=Copy#types-eagerly-implement-common-traits-c-common-traits) recommend eagerly implementing common traits. Since decoders and the `ReadBuf` are views without mutable access into a read-only buffer, there is no harm in copying a decoder (if so, the Rust borrow checker would prevent it from compiling).
> [Rust] Add derive Copy Clone traits for decoders

- sbe-tool/src/main/java/uk/co/real_logic/sbe/json/JsonTokenListener.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/json/JsonPrinterTest.java
SBE toString() won't print trailing garbage after non-printable char; JsonPrinter should have the same functionality...
see CarEncoder toString: 
```
for (int i = 0; i < vehicleCodeLength() && this.vehicleCode(i) > 0; i++)
{
builder.append((char)this.vehicleCode(i));
}
```
> JsonPrinter remove trailing garbage after non-printable char

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/LibRsDef.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
improve rust performance (also more idiomatic)
- specialize `get_u8_at` & `put_u8_at`
- use `copy_from_slice` instead of `split_at` when r/w u8 arrays
> improve rust performance

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/FrameCodecDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/TokenCodecDecoder.java
Handy method should one need to compare the version of the current message to the version of the template.
If the version is identical, we know we can copy the raw bytes, instead of making a field-by-field copy of the message.
> [Java] Expose actingVersion

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/java/ValueRefWithLowerCaseEnum.java
- sbe-tool/src/test/resources/value-ref-with-lower-case-enum.xml
The type identifier was previously used as-is (e.g. `carFilterType`) in
the generated code for uses of `valueRef` while generated Java enums
always start with a capital letter (`CarFilterType`).
See the added test in `ValueRefWithLowerCaseEnum.java`.
> [Java] Support camelCase enum type identifiers for value refs

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
Issue #976
Avoids NPE when set is null when parsing a message in an older protocol version
> [Java] Cope with optional sets not being present when pretty printing decoders for debugging. Issue #976

- .github/workflows/ci.yml
- csharp/sbe-benchmarks/sbe-benchmarks.csproj
- csharp/sbe-dll/sbe-dll.csproj
- csharp/sbe-generated/sbe-generated.csproj
- csharp/sbe-samples-car/sbe-samples-car.csproj
- csharp/sbe-samples-extension/sbe-samples-extension.csproj
- csharp/sbe-tests/sbe-tests.csproj
I've updated the .NET SDK to `8.0`, which is the most recent LTS version. Support ends on 10 November 2026.
There are several C# projects in the SBE solution. Only `sbe-dll` is consumed by users of SBE.
Previously, `sbe-dll` had two targets:
- `.NET Standard 2.0` (2017, supported by `.NET Framework >= 4.6.1` and `.NET Core >= 2.0`, which were both superseded by `.NET`)
- `.NET Framework 4.5` (2012)
In this commit, I have removed the _ancient_ `.NET Framework 4.5` target. This makes it easier to build SBE on Linux, as one only needs a recent .NET installation.
I have also changed the other C# projects to target `.NET 8.0` and updated their dependencies.
> Upgrade .NET SDK to 8.0.201.

- sbe-tool/src/test/cpp/FieldAccessOrderCheckTest.cpp
Small fix to one C++ test.
EXPECT_STREQ macro expects a c-string (i.e. null-terminated), which aOut was not (explicitly).
Extended buffer to accomodate zero byte and explicitly zeroed.
Test was failing on my aging CentOS environment but passes now.
> [C++] small test fix

- rust/tests/baseline_test.rs
- rust/tests/big_endian_test.rs
- rust/tests/extension_test.rs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/LibRsDef.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
> Take slices by reference.

- csharp/sbe-tests/FieldAccessOrderCheckTests.cs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/common/FieldPrecedenceModel.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/FrameCodecDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/generated/TokenCodecDecoder.java
- sbe-tool/src/test/cpp/FieldAccessOrderCheckTest.cpp
- sbe-tool/src/test/java/uk/co/real_logic/sbe/FieldAccessOrderCheckTest.java
- sbe-tool/src/test/resources/field-order-check-schema.xml
Relates to issue #988.
An SBE message might not change in every version of a schema. For example, another message might change.
Previously, the field precedence checking model would expect an exact match for `actingVersion` in `wrap` to enter one of its initial states. However, it is only aware of the versions in which a message schema has changed. Therefore, it was possible for `actingVersion` not to match any of these versions, in which case the initial state that represented a codec wrapped around the latest known version of the format was picked.
Now, we do _not_ expect an exact match in `wrap`. Instead, we select the "best" match. For example, if a codec was changed in v1 and v3, and the acting version is v2, we will decode using v1. However, if the acting version is v4, we would …
> [Java, C#, C++] Fix precedence checks to account for non-contiguous versions.

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/LibRsDef.java
This PR intends to avoid warnings that get generated because of some clippy flags.
We glob re-export  the statics generated within the codecs, which causes issues due to duplicate naming.
In an ideal world, we would stop exporting the statics (or naming them uniquely), but for now I'd like to just avoid the warnings.
Additionally; `get_bytes` is unused and unusable outside of the generated code itself, rendering it useless for any real-world project.
> [Rust] Generation: Avoid warnings

- csharp/sbe-tests/Issue992Tests.cs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpGenerator.java
Hi,
This PR intends to fix [Issue 992](https://github.com/real-logic/simple-binary-encoding/issues/992).
The current generate ToString() implementation calls to `this.BuildString()` which change `this` state.
```
public override string ToString()
{
var sb = new StringBuilder(100);
this.BuildString(sb);
return sb.ToString();
}
```
To avoid the affect ton `this`, I changed the generated `ToString()` to create a new instance of the message, wrap it and then use it with `BuildString()`. This way `this` is not affected.
```
public override string ToString()
{
var sb = new StringBuilder(100);
var m = new GroupAndVarLength();
m.WrapForDecode(_buffer, _offset, _actingBlockLength, _actingVersion);
m.BuildString(sb);
return sb.ToString();
}
```
The assumption is that `ToString()` is only called for …
> [C#] Avoid ToString() affect the message internal state

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
Not sure if this is something you would be willing to accept.
> [Rust] Make Rust crate version configurable.

- rust/tests/baseline_enum_from_str.rs
- rust/tests/baseline_enum_into.rs
- rust/tests/baseline_enum_to_str.rs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
This pr intended to make generated enum items impl FromStr and Display and Into trait.
Usually an enum (in or not in trading) may have two different usecases: either for integer-compitible values (like Side/OrderType) or for string values (like Market).  It's very kind to generate conversion helper for generated Rust enum types.  Currently only `From` was impl for enum types.
1. FromStr trait
Consider a Market enum:
```rust
enum Market {
XSHE, XSHG, 
}
```
A `str` to `Market` conversion was usually needed when dealing with external system.
3. Display trait
See above `Market` enum, a `Display` trait impl was helpful when converting to meaningful string representation for display or presentation purpose.
4. Into trait
As a reverse op of `From`, it is also helpful to get sensible storing …
> [Rust] Enhance enum supporting fromstr and display and into

- rust/tests/baseline_test.rs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/LibRsDef.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
This addresses #1018 .
1. add `SBE_SCHEMA_ID`
2. add `SBE_SCHEMA_VERSION`
3. add `SBE_SEMANTIC_VERSION`
> [Rust] generate message schema level info in lib.rs

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppGenerator.java
- sbe-tool/src/test/cpp/FieldAccessOrderCheckTest.cpp
There were a couple of problems here:
1. "wrapping constructors" did not initialize the codec state (for precedence checks) correctly, and
2. the methods returning a JSON encoded string would attempt to transition twice.
These problems are now resolved.
I have also made a technically breaking change. I have removed an unnecessary constructor that took in the codec state. I think it is highly unlikely that anyone was using this constructor; therefore, it should be okay to make the change.
> [C++] Fix field precedence check issue #1031.

- build.gradle
- rust/Cargo.toml
- rust/tests/baseline_enum_from_str.rs
- rust/tests/extension_test.rs
- rust/tests/fixed_sized_primitive_array.rs
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/LibRsDef.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/rust/RustUtil.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/rust/RustUtilTest.java
- sbe-tool/src/test/resources/fixed-sized-primitive-array-types.xml
code generator for primitive arrays enhancements:
- encoder accepts slice instead of array
- now generates "*_from_iter()"
- now generates  "*_zero_padded()"
> [Rust] encoding primitive arrays now supports slice instead of array (issue #1021)

- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/IrDecoder.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/ir/IrEncoder.java
Fixes https://github.com/aeron-io/simple-binary-encoding/issues/1050
> fix: include field 'deprecated' in ir encoding and decoding

- csharp/sbe-dll/sbe-dll.csproj
So that when you generate the NuGet package, even locally, it uses the correct version automatically
> [C#] Read NuGet package version from version file

- csharp/sbe-dll/sbe-dll.csproj
With this, a consumer of the produced NuGet package does not need to reference the obsolete package System.Memory 4.5.3 anymore, when targeting NETStandard 2.1.
This change still maintains compatibility for consumers who target NETSTandard 2.0, for anyone still running on Full .NET Framework...
> [C#] Enable dual build for netstandard2.0 & netstandard2.1

- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/common/DtoValidationUtil.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/cpp/CppDtoGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/csharp/CSharpDtoGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/generation/java/JavaDtoGenerator.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/json/JsonTokenListener.java
- sbe-tool/src/main/java/uk/co/real_logic/sbe/otf/Types.java
- sbe-tool/src/propertyTest/java/uk/co/real_logic/sbe/properties/DtosPropertyTest.java
- sbe-tool/src/propertyTest/java/uk/co/real_logic/sbe/properties/JsonPropertyTest.java
- sbe-tool/src/propertyTest/java/uk/co/real_logic/sbe/properties/PropertyTestUtil.java
- sbe-tool/src/propertyTest/java/uk/co/real_logic/sbe/properties/arbitraries/SbeArbitraries.java
- sbe-tool/src/propertyTest/java/uk/co/real_logic/sbe/properties/schema/TestXmlSchemaWriter.java
- sbe-tool/src/propertyTest/java/uk/co/real_logic/sbe/properties/utils/InMemoryOutputManager.java
- sbe-tool/src/test/java/uk/co/real_logic/sbe/generation/common/DtoValidationUtilTest.java
Previously, in Java, the generated validation methods would not permit
the null value, even for fields with optional presence. Now, we do allow
these correctly.
In this change, I've also attempted to clean up, centralise, and test
the logic that decides when validation for a particular side of a range
needs to be included. We omit the validation when the native type cannot
represent values outside of the range.
There are still some gaps around validation, e.g., we do not validate
array values.
---
**EDIT**:
The changes above exposed some areas where the OTF JSON printing support in Java did not produce valid JSON, particularly around escaping characters (but also in the representation of some floating-point concepts and some delimiters). I've attempted to improve this area; however, I …
> [Java/C++/C#] Fix a bug in overzealous DTO validation
